apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webapp-pvc
spec:
  resources:
    requests:
      storage: "500Mi"
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
