apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-webapp
spec:
  selector:
    matchLabels:
      app: blue-webapp
  template:
    metadata:
      labels:
        app: blue-webapp
    spec:
      containers:
      - name: blue-webapp
        image: webapp
        env:
        - name: COLOR
          valueFrom:
            configMapKeyRef:
              key: COLOR
              name: blue-cm
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "128Mi"
            cpu: "500m"
