apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-webapp
spec:
  selector:
    matchLabels:
      app: blue-webapp
  replicas: 3
  template:
    metadata:
      labels:
        app: blue-webapp
    spec:
      containers:
      - name: blue-webapp
        image: sohammitra53/webapp:blue_1.2.4
        env:
        - name: COLOR
          value: BLUE
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-cm
              key: MYSQL_USER
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-cm
              key: MYSQL_DATABASE
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: webapp-pv
          mountPath: /home/app/files
        - name: webapp-temp
          mountPath: /home/app/temp
      volumes:
      - name: webapp-pv
        persistentVolumeClaim:
          claimName: blueapp-pvc
      - name: webapp-temp
        emptyDir:
          sizeLimit: 500Mi

