apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-webapp
spec:
  selector:
    matchLabels:
      app: green-webapp
  replicas: 3
  template:
    metadata:
      labels:
        app: green-webapp
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: green-webapp
        image: sohammitra53/webapp:green_1.3.1
        env:
        - name: COLOR
          value: GREEN
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-cm
              key: MYSQL_USER
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-cm
              key: MYSQL_DATABASE
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: webapp-pv
          mountPath: /home/app/files
        - name: webapp-temp
          mountPath: /home/app/temp
      volumes:
      - name: webapp-pv
        persistentVolumeClaim:
          claimName: greenapp-pvc
      - name: webapp-temp
        emptyDir:
          sizeLimit: 500Mi
