apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        envFrom:
        - secretRef:
            name: mysql-secret
        image: mysql:9.6
        resources:
          requests:
            cpu: "0.5"
            memory: 1G
          limits:
            cpu: "2"
            memory: 2G
        ports:
        - containerPort: 1433

