apiVersion: v1
kind: PersistentVolume
metadata:
  name: blueapp-pv
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: webapp-sc
  local:
    path: /root/blueapp
  nodeAffinity:
    required: 
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - training