apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: database
spec:
  storageClassName: mysql-sc
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
