apiVersion: v1
kind: Service
metadata:
  name: blue-webapp
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 32000
  selector:
    app: blue-webapp
  type: NodePort
status:
  loadBalancer: {}
