apiVersion: v1
kind: Service
metadata:
  name: green-webapp
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 32001
  selector:
    app: green-webapp
  type: NodePort
status:
  loadBalancer: {}
